//
//  parking.swift
//  Unticket
//
//  Created by Graphic on 2021-05-25.
//



import Foundation
import FirebaseFirestoreSwift
//
//struct Task:Codable {
//    // add properties of a task here
//    @DocumentID var id:String?     // [OPTIONAL] this will automatically populate the object with the autogenerated document id from Firestore
//    var name:String
//    var priority:Int
//}

import Foundation
struct parking:Codable  {
    var building_code:String

    var date_time:String
    
    var latitude:Double
  
    var license:String
    
    var longitude:Double
   
    var no_hours:Int
    
    var street:String
   
    var suit_number:String
   
    
//    @DocumentID var user_id:String?
 

    
}
